version: '3.4'
services:
  webapp:
    build:
      context: https://github.com/kishorekkota/docker.git
  maria:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=admin
  java:
    image: java
